### PR TITLE
Support for custom authentication drivers

### PR DESCRIPTION
**Pull request by YuriyYatsyk**

### CODE REVIEW

**Comment by YuriyYatsyk** [comment]
@a2ndrade - this PR allows defining "authentication drivers" - basically, users can provide jar(s) and a class that implements Function<String,String>. This class will take connection string in the form of user:password@host:port and should return a string that will be interpreted by the .z.pw function on the q instance. The goal is to allow integration with enterprise SSO systems. E.g. at my company we use kerberos authentication and the absence of kerberos integration is currently the main roadblock for wider adoption of the plugin. 
Any feedback is appreciated.
Thanks -YY

**Comment by YuriyYatsyk** [comment]
You can see the new behavior on the Q settings page - it now has the list of Custom Authentication Drivers. The "Q Server" dialog allows selecting drivers, using default pass-through implementation or defining a new one.

**Comment by YuriyYatsyk** [comment]
Sample implementation:

package com.appian.intellij.k.auth;
import java.util.function.Function;

public class ReverseEncrypt implements Function<String, String> {
  @Override
  public String apply(String s) {
    String[] parts = s.split("@", -1);
    if (parts.length != 2)
      throw newInvalidFormatException();

    String[] userPassword = parts[0].split(":", -1);
    if (userPassword.length != 2)
      throw newInvalidFormatException();

    String password = userPassword[1];
    StringBuilder newPass = new StringBuilder();
    for (int i = 0; i < password.length(); ++i) {
      newPass.append(password.charAt(password.length() - i - 1));
    }
    return userPassword[0] + ":" + newPass.toString();
  }

  private static IllegalArgumentException newInvalidFormatException() {
    return new IllegalArgumentException("Connection string is expected to be in the format 'user:password@host:port'");
  }
}

**Comment by Janiaje** [comment]
@a2ndrade Pls check out this PR, it would help a lot in my job.

**Comment by dayakiran** [comment]
Thanks a lot Yuriy. This is really helpful. I have similar issues at workplace and this would make plugin integration seamless. @a2ndrade Please check this PR.

**Review by a2ndrade — APPROVED** [review]
Thanks, @YuriyYatsyk. Everything looks good to me. The icon looks a bit odd but that's a very minor thing. Thanks for the PR! I'll try to release the new version tonight.

**Comment by YuriyYatsyk** [comment]
@a2ndrade thanks for releasing this quickly. After going through all the bureaucracy this version is finally available at our company internally and seems to have made quite a few of our users happy.

**Pull request merged**
