### PR TITLE
Adds ability to run selected in the editor Q code on configured server(s)

### PR DESCRIPTION
**Pull request by YuriyYatsyk**
@a2ndrade: This is a biggish commit with the following changes:

1. Settings panel for Q allows adding/editing/removing Q servers
server_settings

2. Editor popup menu has 'Run Selection On' submenu that allows sending selected text to one of the configured servers 

run_selection_menu

3. Use Ctrl+Alt+E (smart) or Ctrl+Alt+Shift+E (forced popup) shortcuts to bring up a list of servers/send to active server. Output goes to a per-server console.

run_popup

4. Credentials are persisted in the PasswordSafe

Pls let me know if something needs fixing.

### CODE REVIEW

**Comment by a2ndrade** [comment]
@YuriyYatsyk thanks for the PR. Great functionality! I'll review it and leave any comments I may have during the weekend.

**Comment by a2ndrade** [comment]
@YuriyYatsyk Thanks for the PR. I have a few comments after spending a few minutes trying out the functionality. I think we should address them before merging this increment.

1) What's your vision for how this feature would evolve? Do you have plans to add more capabilities/features on top of it? I'd be very helpful for me to understand the roadmap/backlog you may have.
2) There is some connection state we should clear when the q process dies (and its tab remains opened). Because even after the q process is restarted, sending commands keeps failing until the tab is closed and reopened. 
3) Since q commands cannot be executed correctly (e.g. `\d .some.ns`) the Java code should do more work to sanitize the input sent to the q process. For example, given:
```q
\d .some.ns
myVar:1
```
if I were to select `myVar:1`, we should really be sending `.some.ns.myVar:1` to q. This is especially true if I were to select both lines.
4) We shouldn't allow the user to send invalid/incomplete text to q (that we know is going to fail). Also, related to the point above, I'm not sure if we should allow to send any code other than function definitions and global variables? For example, given:
```q
myFn:{[]
  myVar:1;  // selected line
}
```
what should happen if the `myVar:1` line is selected and sent? currently, that would execute in the global scope of course, but I can't really see why someone would want to do that. That's why I think maybe the more sensible behavior/use case is to maybe? only allow global definitions (functions and/or variables) to be sent.
5) Minor: The `New Server...` option, in the popup menu, should probably be listed **after** the list of already-configured servers so that you that users don't have to always use the down arrow to select the server to send the command to.

**Comment by YuriyYatsyk** [comment]
@a2ndrade Thanks for the comments.

> 1. What's your vision for how this feature would evolve? Do you have plans to add more capabilities/features on top of it?

The feature is meant to address "experimentation" use-case - I (and most of my colleagues) find it extremely useful to be able to test tiny bits of code before including them into a function - I'll provide some examples later, when answering other questions. As to capabilities/features, I was planning to add at least the following:

- Configurable connection/execution timeouts
- A hook for user-provided password handlers - in our company we use kerberos authentication when connecting to q, so simply passing user:password won't work for us. 

Your questions gave me an idea for another feature, more below.

> 2. There is some connection state we should clear when the q process dies

Sure, I'll add reconnection logic.

> 3. Since q commands cannot be executed correctly (e.g. `\d .some.ns`) the Java code should do more work to sanitize the input sent to the q process.

I was treating plugin as just a java-based remote client of a q instance. If you do in q:

```
h:hopen`::9992
h"\\d .foo"
h"bar:3"
```
q will _not_ define .foo.bar, thus I decided not to worry too much about it. 

> if I were to select `myVar:1`, we should really be sending `.some.ns.myVar:1` to q. This is especially true if I were to select both lines.

Again, I am thinking of a plugin as just a remote client and relying on q to do what it thinks is right. Too many developers at my company do most of their work in Q Studio and then paste the code into IntelliJ just because it is much easier to experiment in Q Studio specifically by selecting subsections of the code and running them. I'd like to remove that step and have them play with Q right from IntelliJ.

> 4) We shouldn't allow the user to send invalid/incomplete text to q (that we know is going to fail). 

I am not as ambitious. It sounds like you'd like to provide better error messages than terse q responses. While this is commendable, I don't think it is required for the first version of the feature and I am not sure even if it is necessary at all. 

> Also, related to the point above, I'm not sure if we should allow to send any code other than function definitions and global variables? For example, given:
> 
> ```q
> myFn:{[]
>   myVar:1;  // selected line
> }
> ```
> 
> what should happen if the `myVar:1` line is selected and sent? currently, that would execute in the global scope of course, but I can't really see why someone would want to do that. 

I think executing the line in global scope is just fine. Here are some examples. I am writing a function that requires usage of `sqrt 3`. I would prefer not to compute square root of 3 on every invocation. I type `sqrt 3` in the editor, select, evaluate, get the result and paste it back into the editor as a constant. Another example - I need to write functional `select`. I type `parse "select ..."`, evaluate, get the result back, paste it into editor and tweak as necessary so that the syntax is correct. 
At the end of the day these are q users, they are not used to having guardrails :)

> That's why I think maybe the more sensible behavior/use case is to maybe? only allow global definitions (functions and/or variables) to be sent.

This is an interesting observation. My preference would be not to restrict users in any way (because of the examples above and because I think they can handle it). 
But you make a good point with namespaces and function definitions. I would propose to have a higher level feature (here comes the vision of the backlog :) )  e.g. `Define On <Server>`. This menu item can be made available in the Structure view as well as in the popup menu when a function definition (or global) is selected. When `Define On <Server>` is chosen, we could validate that correct function definition is about to be sent as well as properly handle namespace. What do you think?

> 5) Minor: The `New Server...` option, in the popup menu, should probably be listed **after** the list of already-configured servers so that you that users don't have to always use the down arrow to select the server to send the command to.

The thinking was that users will choose the server menu item once and then would keep hitting the shortcut. But I've no problem moving it to the bottom of the menu, not a sticking point for me at all.

**Comment by YuriyYatsyk** [comment]
@a2ndrade: Added 2 more commits - one to handle reconnection logic, one to move 'New Server...' to the bottom of the menu (I have to admit that it works better this way). 

Pls let me know what you think of my comments - imo, this is a nice, lightweight way to introduce interaction with q instances into plugin. It's the most asked for feature at my company.

**Comment by a2ndrade** [comment]
@YuriyYatsyk checking for malformed/invalid text is relatively straightforward. Just use `KElementFactory.createFile` and pass the selected text. Then you can check if there are errors using `PsiTreeUtil.hasErrorElements`.

**Comment by a2ndrade** [comment]
For us, the most common use-case is to be editing a function or var (in Intellij) and wanting to reload that function/var definition in the q session. Would you find that useful?

For more ad-hoc expression evaluation I usually turn into the q console directly. I'm not opposed to allowing arbitrary expression chunks to be evaluated in the global scope but I do not think it should be the default behavior. I think the default behavior should be "Redefine on" (or similar text) so that you can edit the code and quickly (without even selecting the expression/function) send the definition to q.

I also think that it's very important to make sure the function/var is properly scoped (when sent out). That is, I would want to make the plugin smart enough to understand the fully-qualified name of the identifier (function or var) and send it to q appropriately. 

What do you think? I honestly think you've done the hard work already. The functionality to find the current PSI Element under the cursor is there. `PsiTreeUtil` can be used to find the enclosing function (finding the top-most parent of type `KLambda`), then you need to find the variable being assigned to the lambda and use `KUtil.getFqnOrName` to get the fully-qualified name. I don't remember/know how to print a PSI Tree but it should be possible.

**Comment by YuriyYatsyk** [comment]
@a2ndrade Ok, so we have 2 use-cases - evaluate some random selection and reload the function under cursor (of course this is useful too). How would you structure the menus/shortcuts? I'd like to be able to do both with ease...

**Comment by YuriyYatsyk** [comment]
@a2ndrade There is no "default" behavior - it's a choice of a menu item/shortcut. At the moment I've only implemented the menu item(s) allowing sending selection. In the next update I'll add more menu items/shortcuts to reload/update version of the function/global. I hope such release schedule works for you - we both seem to agree that both features ("run selection" & "redefine function/global") are useful, the question is only if one should go before/together with the other. My preference would be to include the "run selection" in its current state since it is already usable and add "redefine function/global" in the next update.

**Comment by YuriyYatsyk** [comment]
@a2ndrade 

So where are we on this? Will you be able to integrate this PR?

Thanks,
Yuriy

**Comment by YuriyYatsyk** [comment]
@a2ndrade this is not working. bye.

**Comment by a2ndrade** [comment]
@YuriyYatsyk Sorry about the late reply. I was not ignoring your comments, I have very limited connectivity at the moment. There are a few changes I'd like to make (to the current PR) but I'll merge and make them on the master branch.

**Comment by a2ndrade** [comment]
Screen Shot 2019-08-12 at 1 59 22 PM

@YuriyYatsyk I force-pushed a few changes to your branch. If you have any pending work, please rebase as soon as possible to prevent further code conflicts. I formatted your code as shown in the screenshot above. Please, going forward, don't forget to run use the code formatting for the project and run the Intellij auto-formatter 👍

**Comment by YuriyYatsyk** [comment]
Thanks! I am using the formatting settings, but do need to get into a habit to format before committing (there must be a way to automate that, I’ll look into it).

I will pull your changes as soon as I can, most likely over the weekend as I am away at the moment.

Thanks again.

**Pull request merged**
