### PR TITLE
Add gradle build

### PR DESCRIPTION
**Pull request by YuriyYatsyk**
This pull request adds gradle build to the project. The build uses gradle wrapper as described here: https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:adding_wrapper.

In order to get the build to work I had to remove mixing methods from the parser and convert the static KPsiImplUtil methods to instance methods on the KNamedElement. The reason for this is that standalone (outside of intellij) generation of parser does not work well when mixing methods are used since there is a cyclical dependency between KPsiImplUtil and generated code (More info here: https://github.com/JetBrains/Grammar-Kit and here https://github.com/JetBrains/gradle-grammar-kit-plugin)

By moving methods to hand-coded KNamedElement/Impl the cycle is broken. The code also seems to be cleaner since there's no need to have static methods on KPsiImplUtil and also instance methods that simply forward to the util. 

With gradle build you should now be able to easily build, test and even deploy plugin to idea repository - info about intellij gradle plugin and the actions it supports are here: https://github.com/JetBrains/gradle-intellij-plugin

Finally, you may choose to even stop committing intellij project files - idea supports gradle well and you should simply be able to import build.gradle into idea with a few tweaks (like setting up jdk).

I was able to set up continuous integration with teamcity on my private teamcity instance that now runs tests and code coverage based on commits to github, seems to work just fine. Also tested plugin that is built using gradle build, works ok too.

Please let me know if you think this is worth merging into master.

Thanks,
Yuriy Yatsyk

### CODE REVIEW

**Comment by a2ndrade** [comment]
Thanks @YuriyYatsyk! I'll try to find time to review/merge the PR this weekend

**Comment by a2ndrade** [comment]
@YuriyYatsyk I had to cherry-pick your commits because the branch had duplicate commits but all your changes are now in the `master` branch. The setup looks 10x better! Thanks!

**Comment by a2ndrade** [comment]
(I also reformatted all the code to match the project code style so I recommend to rebase as soon as possible)

**Comment by YuriyYatsyk** [comment]
Thanks @a2ndrade! Not sure why I had duplicate commits - I rebased your changes to my master and committed on top of that, must have messed something up, will try to do better job in the future. Will pay more attention to formatting.

**Comment by YuriyYatsyk** [comment]
@a2ndrade - can you advise please in terms of pulling your changes to my fork. I create pull request from main repo to fork and rebase, right? nothing more complicated than that? wan't to make sure no cherrypicking is necessary in the future...
thanks.

**Pull request closed without merging**
